apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: otterstax

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: otterstax

images:
  - name: otterstax/server
    newTag: latest
